### ISSUE TITLE
Nullable Enums throw an error on deserialization

### ISSUE THREAD

**Issue by schiem** [salarcode/Bois#21] opened 2021-12-17 21:59 UTC
Hi there,

I've encountered an issue where attempting to deserialize a nullable enum throws an error.  Here is the minimum reproduction code:

```
using Salar.Bois;

BoisSerializer.Initialize<TestSerializableClass>();

TestSerializableClass options = new TestSerializableClass()
{
    EnumValue = TestEnum.Value1,
};

BoisSerializer serializer = new BoisSerializer();
byte[] bytes;
using (var memoryStream = new MemoryStream())
{
    serializer.Serialize(options, memoryStream);
    bytes = memoryStream.ToArray();
}

using (var memoryStream = new MemoryStream(bytes))
{
    Console.WriteLine(serializer.Deserialize<TestSerializableClass>(memoryStream).EnumValue);
}

public class TestSerializableClass 
{
    public TestEnum? EnumValue { get; set; }
}

public enum TestEnum 
{
    Value1 = 1,
    Value2,
    Value3,
    Value4,
    Value5,
    Value6,
}
```

It appears to be an issue with reading from the stream twice (for example, inside the function `ReadVarInt32Nullable`).  It reads once to check if the value is null or embedded, and then again if the value is not embedded or null.  I suspect that this will be an issue with any non-embedded nullable integer types. 

Seeking backwards by one byte in the stream (e.g. `reader.BaseStream.Seek(-1, SeekOrigin.Current);`) before entering the `ReadInt32Zigzag` function (line 156 of NumericSerializers.cs) appears to fix this issue.  It would need to be done in every Nullable integer read function.

**Comment by salarcode** [comment] 2021-12-31 07:47
Thanks for the sample code, that helped me to reproduce the error.
What you have found was correct, the `ReadVar` method for Enum were reading one byte ahead of what they were supposed to read, but for a very different reason.
This misbehavior is because the write method for Enum is not checking the actual nullability of the property/field, rather it checks the value which is always false if the it is not null.
The fix for this is somewhat simple, the method `EmitGenerator.WriteEnum` needs to cater for the nullable status of the properties.
I'm worried about the binary compatibility of this change, will investigate this before pushing a release, meanwhile i'm pushing the commit with the fix.  Also there seem to be issue with class `Enum`.

**Closed as completed** 2021-12-31 07:47 UTC
