### ISSUE TITLE
Deseriealize problem when child object is null

### ISSUE THREAD

**Issue by gohsianghwee** [salarcode/Bois#8] opened 2016-07-28 03:22 UTC
Hi, 

I encounter some problem during deserialization when Child object is normal class type and it is null. For e.g, when try to deserialize Employee object below will have error if the Child Object Kid is null.

public class Employee
{
   public string Name {get;set}
   public int Age {get;set}
   public Kid Kid { get; set; }
}

public class Kid
{
   public string Name {get;set}
   public int Age {get;set}
}

Thanks for taking time to looking into this issue.

**Comment by salarcode** [comment] 2016-07-30 08:25
Thanks for the report i'm investigating the issue.

**Comment by sunilpraktan** [comment] 2016-08-12 17:11
i'm trying to reproduce the same error but anable to reproduce in separate snippet as per what you expected.
 something is definitely going wrong with my code. one thing is sure that Salar.bios is definitely best and faster tool and i really need it in my ERP product. only because of this issue i'm not sure to integrate this issue. My clients feedback is very good except this issue. this tool is 10 time faster than any other like NetSerilalizer, Proto-Buff, XML,Microsoft,and any other. i have tested all and finally decided to go with this tool. im not getting actually what is going wrong with it. but i will show you the same very soon.
i really appreciate your help to resolve this issue.
Thanks

**Comment by gohsianghwee** [comment] 2016-08-13 06:12
Hi Salar, any idea on the patch? Thanks.

**Comment by salarcode** [comment] 2016-08-13 06:53
The bug is already patched in the previous commit, but the patch breaks backward compatibility which I'm working on it now.

**Comment by gohsianghwee** [comment] 2016-08-15 00:28
Cool. Thanks and I shall keep monitoring.

**Comment by salarcode** [comment] 2016-08-19 08:02
This bug should be fixed now.
Unfortunately this breaks backward compatibility.

**Closed as completed** 2016-08-19 08:01 UTC
Labels: bug
